import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getSession, SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import { AppSidebar } from "@/components/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { UserDropdownMenu } from "@/components/custom/UseDropDownMenu";
import { redirect } from "next/navigation";
import { auth } from "../../../auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tamazight Treasures",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  console.log({ session });

  if (!session.user) {
    redirect("/auth/signin");
  }
  return (
    <html lang={"fr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-14 shrink-0 items-center gap-2 bg-white border-b">
              <div className="flex flex-1 justify-between items-center gap-2 px-3">
                <SidebarTrigger />
                <UserDropdownMenu />
              </div>
              <div className="ml-auto px-3"></div>
            </header>
            <SessionProvider>
              <div className="p-6 h-full">{children}</div>
              <Toaster />
            </SessionProvider>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
